### ISSUE TITLE
Can't change icon once set

### ISSUE THREAD

**Issue by clamage45** [hahagu/WindowsThumbnailGenerator#17] opened 2021-12-04 00:17 UTC
The documentation is very thin, with no explanation for some options, so I figured trial and error would eventually get me what I wanted. But when I was not satisfied with what the folder icon looked like, I found I could not change the icon by running WTG again. I tried with and without _Clear Icon Cache_, and completely exited File Explorer and restarted it.

I thought I could fix the problem by editing `desktop.ini`, but here's the weird thing. Desktop.ini says to use the local `thumb.ico`, and that file **_is_** the changed version. It's just not being picked up by File Explorer. How can I get the displayed icon to correspond to the current `thumb.ico`?

Most of all, I'm hoping the next release will be soon, and use the existing `folder.jpg` for the icon, as in Windows 10. I'm also hoping to be able to use the entire space on the folder for the icon.

**Comment by hahagu** [comment] 2021-12-04 21:31
I have some other work as of now, so I am still working on the new UI.
However, the bug you described, is not really the program's bug, but rather a Windows' bug.
I will take a look, but I do not know if I can even solve it.

**Comment by larsdennert** [comment] 2022-01-04 17:32
deleting the thumb.ico is a temporary work around. You might need to display hidden files to do this manually.

**Comment by clamage45** [comment] 2022-01-04 19:38
Unfortunately, that doesn't quite work, at least on Win11.  What I did:
1. Notice that the folder icon did not match the thumb.ico in the folder.
2. Delete thumb.ico
3. Notice that the folder icon is now a blank folder, no picture.
4. Create new thumb.ico in the folder.
5. Notice that the folder icon now has a picture on it, but it is an old remembered picture, not the new picture, and not the thumb.ico that I removed.

It seems necessary to reboot the computer to get new icons displayed., unless you have another suggestion.

**Comment by hahagu** [comment] 2022-01-08 11:38
It seems that there is a bug with windows 11 regarding folder thumbnails, especially apparent with folders that have many thumbnails.
This could be fixed by clearing the icon cache, and restarting explorer.exe

The documentation does need updating.
However, since this is not exactly the program's fault, I personally think there isn't a solution from my end.
I will look into the problem though.

**Closed as completed by hahagu** 2022-01-08 11:38 UTC

**Comment by larsdennert** [comment] 2022-01-11 19:01
I think the issue is you are making the thumb.ico readonly after creating it but not removing readonly before having imagemagick try to output a new one. Hence the second time it is run, the icon isn't updated. Maybe in unsetsystem proc you need to ~FileAttributes.ReadOnly as well for the thumb.ico or right before it gets written.

 // Set Folder SYSTEM flag, to show thumbnail
            File.SetAttributes(
                targetFolderPath,
                FileAttributes.ReadOnly);



        private static void ExportImage(byte[] sourceImage, string filePath)
        {
            using MagickImage outputImage = new(sourceImage);
            try
            {
               //ADD
              File.SetAttributes(
                filePath,
                ~FileAttributes.ReadOnly);

                outputImage.Write(filePath);
            }
            catch (MagickBlobErrorException)
            {
                return;
            }
        }
